import { invoke } from '@tauri-apps/api/core';
import { buildVukiContext } from '@/services/contextBuilder';
import type { UserProfile, Project, ClaudeLogEntry, Prompt } from '@/types';

interface ClaudeMdInput {
  profile: UserProfile;
  project: Project;
  claudeLogs: ClaudeLogEntry[];
  topPrompts: Prompt[];
}

export async function generateAndSaveClaudeMd(input: ClaudeMdInput): Promise<string> {
  const { profile, project, claudeLogs, topPrompts } = input;

  if (!project.folderPath) {
    throw new Error(`Project "${project.name}" has no folder path configured`);
  }

  // Filter Claude logs for this project (last 3)
  const projectLogs = claudeLogs
    .filter(log => log.projectId === project.id)
    .slice(0, 3);

  const logsText = projectLogs.length > 0
    ? projectLogs
      .map(log => `- [${new Date(log.createdAt).toLocaleDateString()}]: ${log.summary}`)
      .join('\n')
    : 'No Claude activity yet on this project.';

  // Filter prompts by project tags (top 3)
  const projectPrompts = topPrompts
    .filter(p => project.tags.some(tag => p.tags.includes(tag)))
    .slice(0, 3);

  const promptsText = projectPrompts.length > 0
    ? projectPrompts
      .map(p => `- **${p.label}** (${p.category})`)
      .join('\n')
    : 'No relevant prompts tagged to this project yet.';

  // Build markdown
  const markdown = `# CLAUDE.md — VukiXX Context
_Auto-generated by VukiXX. Last updated: ${new Date().toISOString()}_

## Who I am

**Name:** ${profile.name}
**Role:** ${profile.role}
**Stack:** ${profile.preferredStack.join(', ') || 'Not specified'}
**Communication style:** ${profile.communicationStyle}
**Language:** ${profile.preferredLanguage === 'sr' ? 'Srpski' : 'English'}

---

## Active Project: ${project.name}

**Goal:** ${project.goal}
**Status:** ${project.status}
**Priority:** ${project.priority}
**Next step:** ${project.nextStep || 'Not specified'}
**Tags:** ${project.tags.join(', ') || 'None'}

---

## Recent Claude Activity on This Project

${logsText}

---

## My Top Prompts for This Project

${promptsText}

---

## Instructions for Claude

- Always respond in **${profile.preferredLanguage === 'sr' ? 'Srpski' : 'English'}**
- Communication style: **${profile.communicationStyle}**
- Don't ask what I know — start working immediately
- Focus on "Next step" above
- When done, summarize what you did in 3 bullet points
- If you need context, check the project folder for related files

---

_This file is auto-generated. Edit project details in VukiXX to regenerate._
`;

  // Write to project folder
  const fullPath = await invoke<string>('write_claude_md', {
    project_path: project.folderPath,
    content: markdown,
  });

  console.log(`✅ [ClaudeMdGenerator] CLAUDE.md saved to: ${fullPath}`);
  return fullPath;
}
